Add git cion score to donation flow
GeneralMagicio/QAcc-BE pull request #142
Opened 2024-11-24 23:57 UTC by ae2079

2024-11-25 07:22 UTC, MohammadPCh approved these changes
@ae2079  Thanks for the PR! It looks great to me, but since Carlos is the HERO of this part, I’d recommend having him review it as well to ensure everything is spot on. 😊

2024-11-25 07:29 UTC, MohammadPCh commented
Also, @aminlatifi is the Hero of this part

2024-11-25 09:02 UTC, aminlatifi requested changes
Please update the name of variables to be better self explainatory

2024-11-25 09:02 UTC, aminlatifi commented on config/example.env
> +VALID_SCORE_TIMESTAMP=86400000
```suggestion
GITCOINT_PASSPORT_EXPIRATION_PERIOD_MS=86400000
```

2024-11-25 09:02 UTC, aminlatifi commented on config/example.env
> +GITCOIN_MIN_SCORE=
```suggestion
GITCOIN_PASSPORT_MIN_VALID_SCORE=
```

2024-11-25 09:41 UTC, aminlatifi requested changes

2024-11-25 09:41 UTC, aminlatifi commented on src/entities/user.ts
> +  passportScoreUpdateTimestamp?: string;
We have examples of using timestampz
```
  @Field(_type => Date, { nullable: true })
  @Column({ type: 'timestamptz', nullable: true })
  ```
  We don't need to convert time to string and save in backend.

2024-11-25 09:41 UTC, aminlatifi commented on src/utils/qacc.ts
> +    Boolean(config.get('ACTIVATE_GITCOIN_SCORE_CHECK')) &&
What if that flag is false? we shouldn't check the zkID?!

2024-11-25 09:41 UTC, aminlatifi commented on src/services/qAccService.ts
> +      Date.now() - (Number(config.get('VALID_SCORE_TIMESTAMP')) || 86400000) // default value is 1 day
Move this default filling to `src/constants/qacc.ts`

2024-11-25 09:41 UTC, aminlatifi commented on src/services/qAccService.ts
> +    user.passportScore < Number(config.get('GITCOIN_MIN_SCORE'))
likewise

2024-11-25 09:41 UTC, aminlatifi commented on src/services/qAccService.ts
> +      `passport score is less than ${config.get('GITCOIN_MIN_SCORE')}`,
Likewise

2024-11-25 09:41 UTC, aminlatifi commented on src/services/qAccService.ts
> +    Number(config.get('MAX_AMOUNT_NO_KYC')) - qfTotalDonationAmount;
Likewise

2024-11-25 09:41 UTC, aminlatifi commented on src/resolvers/donationResolver.ts
> +  async validateDonation(
I would name it differently, like `checkDonationValidity`

2024-11-25 12:36 UTC, aminlatifi commented on src/entities/user.ts
I think it can be helpful to have a getter field  (like privadoVerified) that show user has enough gitcoin passport. In this case we don't need to share the required gitcoin passport score with FE

2024-11-26 01:19 UTC, ae2079 commented on src/utils/qacc.ts
> +    Boolean(config.get('ACTIVATE_GITCOIN_SCORE_CHECK')) &&
the flow remained as before, and we check zkID in other place

2024-11-26 06:00 UTC, aminlatifi commented
https://github.com/Giveth/giveth-dapps-v2/issues/4221

2024-11-26 06:25 UTC, aminlatifi requested changes

2024-11-26 06:25 UTC, aminlatifi commented on src/entities/user.ts
> +  get hasEnoughAnalysisScore(): boolean {
```suggestion
  get hasEnoughGitcoinAnalysisScore(): boolean {
```

2024-11-26 06:25 UTC, aminlatifi commented on src/entities/user.ts
> +      this.analysisScore >= GITCOIN_PASSPORT_MIN_VALID_SCORE
If we want to compare with analysisScore, let's change this variable name as well
GITCOIN_PASSPORT_MIN_VALID_SCORE -> GITCOIN_PASSPORT_MIN_VALID_ANALYSIS_SCORE

2024-11-26 06:25 UTC, aminlatifi commented on src/resolvers/qAccResolver.ts
> +}
Instead of two, we could define one with general name

2024-11-26 06:25 UTC, aminlatifi commented on src/services/qAccService.ts
> +} from '../constants/qacc';
I didn't communicate it well. I meant to create a new file under `../constants` folder for passport related constants

2024-11-26 06:25 UTC, aminlatifi commented on src/services/qAccService.ts
> +      Date.now() - GITCOIN_PASSPORT_EXPIRATION_PERIOD_MS
Two points, 
1. It seems it must be to make sense
```suggestion
    user.passportScoreUpdateTimestamp.getTime() <
      Date.now() - GITCOIN_PASSPORT_EXPIRATION_PERIOD_MS
```
2. It seems we don't update passportScoreUpdateTimestamp anymore in  `updateUserGitcoinAnalysisScore`. Please revise the way it's used.

2024-11-26 13:51 UTC, aminlatifi requested changes

2024-11-26 13:51 UTC, aminlatifi commented on src/services/userService.ts
> +};
Please remove this, it's only used once and has a similar meaning of `findUserById`.

2024-11-26 14:11 UTC, aminlatifi approved these changes
Thanks @ae2079 
Great job

2024-11-26 14:11 UTC, aminlatifi commented on config/example.env
> +MAX_CONTRIBUTION_WITH_GITCOIN_PASSPORT_ONLY_IN_USD=
```suggestion
MAX_CONTRIBUTION_WITH_GITCOIN_PASSPORT_ONLY_USD=
```

2024-11-26 14:15 UTC, merged