Use code for email verification
GeneralMagicio/QAcc-BE pull request #25
Opened 2024-08-17 23:32 UTC by ae2079

#16

2024-08-18 07:30 UTC, aminlatifi requested changes

2024-08-18 07:30 UTC, aminlatifi commented on test/graphqlQueries.ts
> +      emailConfirmationCode
We should not return email confirmation code in response! it must be kept private in our backend

2024-08-18 07:30 UTC, aminlatifi commented on test/graphqlQueries.ts
> +      emailConfirmationCode
And here the user should not be able to see it

2024-08-18 13:24 UTC, ae2079 commented on test/graphqlQueries.ts
> +      emailConfirmationCode
You are right, but this is only for testing, and in the actual resolver, the user can access them because we return all user data, should we define an interface for user presentation?

2024-08-18 13:24 UTC, ae2079 commented on test/graphqlQueries.ts
> +      emailConfirmationCode
by the way, I changed it :)

2024-08-18 14:37 UTC, aminlatifi requested changes

2024-08-18 14:37 UTC, aminlatifi commented on src/resolvers/userResolver.ts
>        return userToVerify;
The problem is not solved! the verification code is part of the user entity which can be fetched via queries like `userByAddress`. 
I suggest creating a separate table for holding confirmation token and don't join it with the User entity at all.

2024-08-18 14:37 UTC, aminlatifi commented on migration/1723936796571-RenameUserEmailVerificationFields.ts
> +import { MigrationInterface, QueryRunner } from 'typeorm';
As we discussed, we don't need to bother ourselves at this stage and write migration for each change. The `sync` flag is true on staging and it will be so far. We will create a single total migration when the backend becomes stable

2024-08-19 00:39 UTC, ae2079 commented on src/resolvers/userResolver.ts
>        return userToVerify;
yeah, I'll do that

2024-08-19 08:07 UTC, aminlatifi requested changes

2024-08-19 08:07 UTC, aminlatifi commented on src/entities/user.ts
> +
This relation should be omitted. We don't need it and also it causes issues as typeorm needs a join column to match entities.

2024-08-19 08:07 UTC, aminlatifi commented on src/entities/userEmailVerification.ts
> +  user: User;
Again, no relation is needed. Just a column `userId` with number type to manually find the record from user id

2024-08-19 14:01 UTC, aminlatifi approved these changes
LGTM!
Thanks @ae2079

2024-08-19 16:35 UTC, merged