WIP: Adding token_price column to rounds
GeneralMagicio/QAcc-BE pull request #65
Opened 2024-09-23 15:00 UTC by kkatusic

2024-09-24 08:10 UTC, aminlatifi requested changes
Great job @kkatusic so far, just few changes. Also, please write unit tests for them

2024-09-24 08:10 UTC, aminlatifi commented on src/repositories/earlyAccessRoundRepository.ts
> +    if (round.tokenPrice === null) {
It's redundant we had the check in SQL query

2024-09-24 08:10 UTC, aminlatifi commented on src/repositories/earlyAccessRoundRepository.ts
> +    .where('earlyAccessRound.token_price IS NULL')
We need another `andWhere` line to filter rounds their start time are in the future

2024-09-24 08:10 UTC, aminlatifi commented on src/repositories/earlyAccessRoundRepository.ts
> +        symbol: 'POL',
We have `QACC_DONATION_TOKEN_COINGECKO_ID` in src/utils/qacc.ts, you can use that as coingecko symbol here

2024-09-24 09:33 UTC, kkatusic commented on src/repositories/earlyAccessRoundRepository.ts
> +    .where('earlyAccessRound.token_price IS NULL')
thx @aminlatifi , removed condition

2024-09-24 09:34 UTC, kkatusic commented on src/repositories/earlyAccessRoundRepository.ts
> +    if (round.tokenPrice === null) {
thx @aminlatifi , removed

2024-09-24 09:40 UTC, kkatusic commented on src/repositories/earlyAccessRoundRepository.ts
> +    .where('earlyAccessRound.token_price IS NULL')
thx @aminlatifi , added additional where condition to query

2024-09-24 09:57 UTC, kkatusic commented on src/repositories/earlyAccessRoundRepository.ts
> +        symbol: 'POL',
thx @aminlatifi , it is `QACC_DONATION_TOKEN_SYMBOL` just to notice here if someone read it in future :)

2024-09-24 11:36 UTC, ae2079 commented on migration/1727098387189-addTokenPriceToRounds.ts
> +      `ALTER TABLE "qf_round" ADD "token_price" double precision DEFAULT NULL`,
I think if we can have the date of the price, it would be better and help in case any bugs happen

2024-09-24 12:13 UTC, kkatusic commented on migration/1727098387189-addTokenPriceToRounds.ts
> +      `ALTER TABLE "qf_round" ADD "token_price" double precision DEFAULT NULL`,
@aminlatifi what you think?

2024-09-25 11:45 UTC, aminlatifi requested changes

2024-09-25 11:45 UTC, aminlatifi commented on src/repositories/earlyAccessRoundRepository.ts
> +  }
It's not necessary

2024-09-25 11:45 UTC, aminlatifi commented on src/repositories/earlyAccessRoundRepository.ts
> +      symbol: 'polygon-ecosystem-token',
we have `QACC_DONATION_TOKEN_COINGECKO_ID`

2024-09-25 11:45 UTC, aminlatifi commented on src/repositories/earlyAccessRoundRepository.ts
> +      date: formattedDate,
It was wrong from the begining to pass the date in formated string version. I forces us to format date everytime we want to call it.
Let's change the parameter type to accept js date and do the formatting once inside the adapter. Also, update everywhere else it was called.

2024-09-25 11:45 UTC, aminlatifi commented on src/repositories/earlyAccessRoundRepository.test.ts
> +    expect(updatedEarlyAcccessRound?.tokenPrice).to.equal(100);
As mentioned before, the price must be resolved at the round start time. It would be beneficial to use sinon assert to check the token price is resolved at correct point `sinon.assert.calledWith(spyOrSpyCall, arg1, arg2, ...);`

2024-09-25 13:05 UTC, kkatusic commented on src/repositories/earlyAccessRoundRepository.ts
> +      symbol: 'polygon-ecosystem-token',
thx @aminlatifi, condition removed

2024-09-25 13:20 UTC, aminlatifi commented on src/repositories/earlyAccessRoundRepository.ts
> +    .where('earlyAccessRound.token_price IS NULL')
I meant, the start time must be in the past

2024-09-25 13:23 UTC, kkatusic commented on src/repositories/earlyAccessRoundRepository.ts
> +      date: formattedDate,
thx @aminlatifi , added formatting date option inside adapter function and changed on all scripts where it has been used

2024-09-25 13:30 UTC, kkatusic commented on src/repositories/earlyAccessRoundRepository.ts
> +  }
thx @aminlatifi, removed

2024-09-25 14:03 UTC, kkatusic commented on src/repositories/earlyAccessRoundRepository.ts
> +      symbol: 'polygon-ecosystem-token',
@aminlatifi for some reason that constant isn't available in test case `QACC_DONATION_TOKEN_COINGECKO_ID`, we lost some time because of that to figured out why tests were failing.

2024-09-25 14:16 UTC, kkatusic commented on src/repositories/earlyAccessRoundRepository.test.ts
> +    expect(updatedEarlyAcccessRound?.tokenPrice).to.equal(100);
ok @aminlatifi , test updated

2024-09-25 19:05 UTC, kkatusic commented on src/repositories/earlyAccessRoundRepository.ts
> +    .where('earlyAccessRound.token_price IS NULL')
You mean if we define all round at one, that query select only ones that start time is older than now?

2024-09-26 09:16 UTC, aminlatifi commented on src/repositories/earlyAccessRoundRepository.ts
> +      symbol: 'polygon-ecosystem-token',
Read it from qacc.ts
```
export const QACC_DONATION_TOKEN_COINGECKO_ID =
  (config.get('QACC_DONATION_TOKEN_COINGECKO_ID') as string) || 'matic-network';
  ```

2024-09-26 09:16 UTC, aminlatifi commented on src/repositories/qfRoundRepository.ts
> +    .where('qf_round.tokenPrice IS NULL')
The begin date must not be in the future

2024-09-26 09:16 UTC, aminlatifi commented on src/repositories/earlyAccessRoundRepository.ts
> +    .where('early_AccessRound.tokenPrice IS NULL')
The start date must not be in the future

2024-09-26 11:02 UTC, kkatusic commented on src/repositories/earlyAccessRoundRepository.ts
> +      symbol: 'polygon-ecosystem-token',
@aminlatifi , I can read variable and it is ok, but for some reasons same variables aren't loaded when you run test :( Did't figurate out what is removing or overriding variables when test is running

2024-09-26 12:16 UTC, aminlatifi commented on src/repositories/earlyAccessRoundRepository.ts
> +    .where('earlyAccessRound.token_price IS NULL')
Exactly, otherwise, we cannot set the price.

2024-09-26 12:55 UTC, kkatusic commented on src/repositories/qfRoundRepository.ts
> +    .where('qf_round.tokenPrice IS NULL')
thx @aminlatifi added date check

2024-09-26 12:55 UTC, kkatusic commented on src/repositories/earlyAccessRoundRepository.ts
> +    .where('early_AccessRound.tokenPrice IS NULL')
thx @aminlatifi added date check

2024-09-27 15:21 UTC, merged